### ISSUE TITLE
Game build fails with Adventure Reforged on GB Studio 4.1.3

### ISSUE THREAD

**Issue by re4mat** [shin-gamedev/gbs-plugins#1]
## Environment
**Operating System:** Debian 12 (x64)
**GB Studio Version:** 4.1.3 (.deb)
**Plugins Installed:**
* Adventure Reforged (8212746)

## Description
When attempting to build the game, the build fails with the following output in the debugger pane:

```
Compiling: src/states/states_ptrs.s 
src/states/adventure.c:44: error 47: indirections to different types assignment    
from type 'struct point16_t data' 
  to type 'struct upoint16_t fixed' 
1 
Cancelled Build 

Warnings:
Plugin "Adventure Reforged (4.0.0)" was created for an older version of GB Studio and may not work correctly. Plugin uses engine "4.0.0-e0" but GB Studio is using engine "4.2.0-e1". 
src/states/adventure.c:44: error 47: indirections to different types assignment    
from type 'struct point16_t data' 
  to type 'struct upoint16_t fixed' 
1
```

## Expected Result
Game should build successfully.

## Steps to Reproduce
1. In GB Studio 4.1.3, create a new Adventure project.
2. Install Adventure Reforged.
3. Click run button to build the game.
Result: Build cancels.

## Workaround / Proposed Fix
I was able to get the game to build by changing line 44 on `src/states/adventure.c` from

```
    old_pos = PLAYER.pos;
```

to

```
    old_pos.x = PLAYER.pos.x;
    old_pos.y = PLAYER.pos.y;
```

**Comment by shin-gamedev** [comment]
Pushed a 4.1.2 compatible version that should fix the issue. Recent GBS version changed positions from unsigned to signed, just had to update to match that.
